version: '3.4'

services:
  redisdb:
    container_name: redisdb
    image: redis:latest
    ports:
      - "6379:6379"
  background.worker:
    image: ${DOCKER_REGISTRY-}backgroundworker
    restart: always
    build:
      context: .
      dockerfile: src/Background.Worker/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"