version: '3.4'

services:
  redisdb:
    container_name: redisdb
    image: redis:latest
    ports:
      - "6379:6379"
  background.worker:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_ENVIRONMENT=Development
      - "RedisSettings:ConnectionString=redisdb:6379"
    depends_on:
      - redisdb
    ports:
      - "5000:5000"
      - "5001:5001"